// @ts-check
// This file is automatically generated by Wails on build. The version checked
// in here mirrors app.go / app_*.go bindings so the dev environment can
// resolve imports without a fresh `wails generate`.

export function Toggle() {
    return window['go']['main']['App']['Toggle']();
}

export function GetState() {
    return window['go']['main']['App']['GetState']();
}

export function GetProxyIP() {
    return window['go']['main']['App']['GetProxyIP']();
}

export function UpdateProxyIP(ip) {
    return window['go']['main']['App']['UpdateProxyIP'](ip);
}

export function IsMacOS() {
    return window['go']['main']['App']['IsMacOS']();
}

export function Quit() {
    return window['go']['main']['App']['Quit']();
}

export function SubmitSudoPassword(pw) {
    return window['go']['main']['App']['SubmitSudoPassword'](pw);
}

export function HasSudoPassword() {
    return window['go']['main']['App']['HasSudoPassword']();
}
